os: osx
osx_image: xcode6.4
language: objective-c
xcode_project: SimpleSynth.xcodeproj
script: xcodebuild -configuration Release -arch x86_64
before_deploy: zip SimpleSynth.app /Users/travis/build/marnen/simplesynth/build/Release/SimpleSynth.app

deploy:
  provider: releases
  file: SimpleSynth.app.zip
  on:
    tags: true
  draft: true
